peakaboo:
  build: ..
  environment:
    - MONGO_URL=mongodb://peakabooMongo:27017/peakaboo
    - MONGO_OPLOG_URL=mongodb://peakabooMongo:27017/local
    - SERVER_NAME
    - METEOR_SETTINGS
  links:
    - peakabooMongo
  restart: on-failure

peakabooMongo:
  image: mongo:3
  entrypoint: [ "/usr/bin/mongod",
                "--replSet", "peakaboo",
                "--oplogSize", "128",
                "--storageEngine", "wiredTiger",
                "--smallfiles" ]
  volumes:
    - ./mongo/db:/data/db
  restart: on-failure

peakabooMongoSetup:
  image: mongo:3
  links:
    - peakabooMongo
  volumes:
    - ./mongo:/scripts
  entrypoint: [ "/scripts/setupmongo" ]

peakabooNginx:
  image: nginx
  command: /etc/nginx/startnginx
  environment:
    - SERVER_NAME
  volumes:
    - ./nginx:/etc/nginx
  links:
    - peakaboo
  ports:
    - "80:80"
    - "443:443"
  restart: on-failure
